#include "types.h"
extern const mesh_t stickman_legs_mesh;
extern const struct anim_step legs_walk;
extern const mesh_t stickman_torso_mesh;
extern const struct anim_step torso_big_swing_1;
extern const struct anim_step torso_big_swing_2;
extern const struct anim_step torso_big_swing_3;
extern const struct anim_step torso_big_swing_4;
extern const struct anim_step torso_lo_unblock_1;
extern const struct anim_step torso_lo_unblock_2;
extern const struct anim_step torso_lo_unblock_3;
extern const struct anim_step torso_hi_unblock;
extern const struct anim_step torso_bottom;
extern const struct anim_step torso_top;
extern const struct anim_step torso_hi_block;
extern const struct anim_step torso_unlunge;
extern const struct anim_step torso_lunge;
extern const struct anim_step torso_lift_1;
extern const struct anim_step torso_lift_2;
extern const struct anim_step torso_overhead;
extern const struct anim_step torso_block;
extern const struct anim_step torso_swing_1;
extern const struct anim_step torso_swing_2;
extern const struct anim_step torso_forward;
extern const struct anim_step torso_unlift_1;
extern const struct anim_step torso_unlift_2;
extern const struct anim_step torso_lo_block_1;
extern const struct anim_step torso_lo_block_2;
extern const struct anim_step torso_lo_block_3;
extern const struct anim_step torso_swingup_1;
extern const struct anim_step torso_swingup_2;
