#include "types.h"
extern const mesh_t stickman_legs_mesh;
extern const struct anim_step legs_walk;
extern const struct anim_step legs_null_A;
extern const struct anim_step legs_null_B;
extern const mesh_t stickman_torso_mesh;
extern const struct anim_step torso_big_swing_1;
extern const struct anim_step torso_big_swing_2;
extern const struct anim_step torso_big_swing_3;
extern const struct anim_step torso_big_swing_4;
extern const struct anim_step torso_swing_1;
extern const struct anim_step torso_swing_2;
extern const struct anim_step torso_lunge;
extern const struct anim_step torso_lift_1;
extern const struct anim_step torso_lift_2;
extern const struct anim_step torso_hi_block;
extern const struct anim_step torso_lo_block_1;
extern const struct anim_step torso_lo_block_2;
extern const struct anim_step torso_lo_block_3;
extern const struct anim_step torso_null_Swing_mid;
extern const struct anim_step torso_null_Twirl_Block;
extern const struct anim_step torso_null_Bottom;
extern const struct anim_step torso_null_Top;
extern const struct anim_step torso_null_Overhead;
extern const struct anim_step torso_null_Twirl_2;
extern const struct anim_step torso_null_Forward;
extern const struct anim_step torso_null_Twirl_1;
extern const struct anim_step torso_null_Over_Mid;
extern const struct anim_step torso_null_Block;
