typedef const struct mesh* mesh_t;
typedef struct anim_mesh* anim_mesh_t;
typedef const struct animation* animation_t;

extern anim_mesh_t stickman;
extern struct animation stickman_unlunge;
extern struct animation stickman_lift;
extern struct animation stickman_hi_dodge;
extern struct animation stickman_overhead;
extern struct animation stickman_step_bottom;
extern struct animation stickman_forward;
extern struct animation stickman_lo_dodge;
extern struct animation stickman_big_swing;
extern struct animation stickman_poke;
extern struct animation stickman_lunge;
extern struct animation stickman_swing_up;
extern struct animation stickman_lo_unblock;
extern struct animation stickman_rest;
extern struct animation stickman_hi_unblock;
extern struct animation stickman_block;
extern struct animation stickman_swing;
extern struct animation stickman_drop;
extern struct animation stickman_unlift;
extern struct animation stickman_hi_block;
extern struct animation stickman_step_top;
extern struct animation stickman_top;
extern struct animation stickman_bottom;
extern struct animation stickman_lo_block;
