typedef struct shader* shader_t;
extern shader_t anim_vert;
extern shader_t blast_frag;
extern shader_t blit_frag;
extern shader_t color_frag;
extern shader_t health_bar_vert;
extern shader_t particles_vert;
extern shader_t screenspace_vert;
extern shader_t simple_vert;
extern shader_t waves_frag;
